name: Tests configuration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
        
    - name: Restore dependencies
      run: dotnet restore ./ToDo/
           
   #- name: Clean
    # run: dotnet clean ./ToDo/ToDo.sln --configuration Release && dotnet nuget locals all --clear
      
    - name: Build
      run: dotnet build --configuration Release --no-restore ./ToDo
      
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release ./ToDo
